apiVersion: apps/v1
kind: Deployment
metadata:
  name: watexr
  labels:
    app: watexr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watexr
  template:
    metadata:
      labels:
        app: watexr
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: cloud.google.com/gke-preemptible
                    operator: NotIn
                    values:
                      - 'true'
      containers:
      - name: watexr
        image: app-image
        resources:
          requests:
            memory: 512Mi
        ports:
          - containerPort: 8866
        livenessProbe:
          httpGet:
            path: /voila/static/main.js
            port: 8866
          initialDelaySeconds: 3
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /voila/static/main.js
            port: 8866
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: watexr
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  ports:
  - port: 8866
    protocol: TCP
  selector:
    app: watexr
